In [10]:
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv("credit_card.csv")

In [4]:
df.head()

,gender,age,job,marital,education,default,housing,loan,contact,CreditCard
0,female,56,housemaid,married,basic.4y,no,no,no,telephone,no
1,male,57,services,married,high.school,yes,no,no,telephone,no
2,female,37,services,married,high.school,no,yes,no,telephone,no
3,female,40,admin.,married,basic.6y,no,no,no,telephone,no
4,female,56,services,married,high.school,no,no,yes,telephone,no

In [6]:
df.shape

(41188, 10)

In [7]:
df.describe()

               age
count  41188.00000
mean      40.02406
std       10.42125
min       17.00000
25%       32.00000
50%       38.00000
75%       47.00000
max       98.00000

In [11]:
df.describe(include=["object", "category"])

,gender,job,marital,education,default,housing,loan,contact,CreditCard
count,41188,41188,41188,41188,41188,41188,41188,41188,41188
unique,2,12,4,8,2,2,2,2,2
top,female,admin.,married,university.degree,no,yes,no,cellular,no
freq,20798,10422,24928,12168,32588,22566,33950,26144,36548

# Q1: What is the Probability that the Customer has a Credit Card?

In [83]:
total_customers = df["CreditCard"].count()
has_credit_card = df[df["CreditCard"] == "yes"]["CreditCard"].count()
print(round((has_credit_card / total_customers) * 100, 3), "%")

11.265 %

# Q2: What is the Probability that the Customer age is greated than 50?

In [29]:
print(round((df["age"] > 50).mean() * 100, 3), "%")

17.4 %

# Q3. What is the probability that the Customer is illiterate?

In [82]:
print( round( ( df["education"] == "illiterate").mean() * 100, 10 ), "%")

0.0437020491 %

# Q4: What is the probability that the Customer has a Telephone?

In [58]:
print(round((df["contact"] == "telephone").mean() * 100, 3), "%")

36.5 %

# Q5: What is the Probability that the Customer is Singe and has a Credit Card?

In [57]:
print(round(((df.marital == "single") & (df.CreditCard == "yes")).mean() * 100, 3), "%")

3.933 %

# Q6: What is the probability that the Customer is Male and has at most 6 Year of Education?

In [75]:
has_at_most_6_y = (df.education.isin(["illiterate", "unknown", "basic.4y", "basic.6y"]))
is_male = (df.gender == "male")
is_male_and_at_most_6_y = (has_at_most_6_y & is_male).mean()
print(round(is_male_and_at_most_6_y * 100, 3), "%")

9.8 %

# Q7: What is the probability that the Customer is Retired and is divorced?

In [84]:
is_retired = df.job == "retired"
is_divorced = df.marital == "divorced"
print(round((is_retired & is_divorced).mean() * 100, 3), "%")

0.845 %

# Q8: Given the Customer has the credit card, find the probability that he/she is married?

In [94]:
has_card_and_married = (df[df["CreditCard"] == "yes"]["marital"] == "married").mean()
print(round(has_card_and_married.mean() * 100,3), "%")

54.569 %

# Q9: If a customer has a management job, find the probability that he has a housing?

In [100]:
managment_job_and_housing = (df[df["job"] == "management"]["housing"] == "yes").mean()
print(round(managment_job_and_housing.mean() * 100,3), "%")

53.386 %

<h1 align="center" style="color: red;">Part 2: Bayes Theorem</h1>

In [111]:
df = pd.read_csv("kerala_floods.csv")

In [104]:
df.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL,FLOODS
0,KERALA,1901,28.7,44.7,51.6,160.0,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,3248.6,YES
1,KERALA,1902,6.7,2.6,57.3,83.9,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,3326.6,YES
2,KERALA,1903,3.2,18.6,3.1,83.6,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,3271.2,YES
3,KERALA,1904,23.7,3.0,32.2,71.5,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,3129.7,YES
4,KERALA,1905,1.2,22.3,9.4,105.9,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,2741.6,NO

In [105]:
df.shape

(118, 16)

In [106]:
df.isna().count()

SUBDIVISION         118
YEAR                118
JAN                 118
FEB                 118
MAR                 118
APR                 118
MAY                 118
JUN                 118
JUL                 118
AUG                 118
SEP                 118
OCT                 118
NOV                 118
DEC                 118
 ANNUAL RAINFALL    118
FLOODS              118
dtype: int64

### 1. preparation

In [116]:
df["JUNE_MORE_THAN_500"] = (df.JUN > 500).astype(int)
df["IS_FLOODS"] = (df.FLOODS == "YES").astype(int)
df

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL,FLOODS,IS_FLOODS,JUNE_MORE_THAN_500
0,KERALA,1901,28.7,44.7,51.6,160.0,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,3248.6,YES,1,1
1,KERALA,1902,6.7,2.6,57.3,83.9,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,3326.6,YES,1,0
2,KERALA,1903,3.2,18.6,3.1,83.6,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,3271.2,YES,1,1
3,KERALA,1904,23.7,3.0,32.2,71.5,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,3129.7,YES,1,1
4,KERALA,1905,1.2,22.3,9.4,105.9,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,2741.6,NO,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,KERALA,2014,4.6,10.3,17.9,95.7,251.0,454.4,677.8,733.9,298.8,355.5,99.5,47.2,3046.4,YES,1,0
114,KERALA,2015,3.1,5.8,50.1,214.1,201.8,563.6,406.0,252.2,292.9,308.1,223.6,79.4,2600.6,NO,0,1
115,KERALA,2016,2.4,3.8,35.9,143.0,186.4,522.2,412.3,325.5,173.2,225.9,125.4,23.6,2176.6,NO,0,1
116,KERALA,2017,1.9,6.8,8.9,43.6,173.5,498.5,319.6,531.8,209.5,192.4,92.5,38.1,2117.1,NO,0,0
117,KERALA,2018,29.1,52.1,48.6,116.4,183.8,625.4,1048.5,1398.9,423.6,356.1,125.4,65.1,4473.0,YES,1,1

### 2. Select benefit columns

In [118]:
bc = df[["FLOODS", "IS_FLOODS", "JUN", "JUNE_MORE_THAN_500"]]
bc

    FLOODS  IS_FLOODS     JUN  JUNE_MORE_THAN_500
0      YES          1   824.6                   1
1      YES          1   390.9                   0
2      YES          1   558.6                   1
3      YES          1  1098.2                   1
4       NO          0   850.2                   1
..     ...        ...     ...                 ...
113    YES          1   454.4                   0
114     NO          0   563.6                   1
115     NO          0   522.2                   1
116     NO          0   498.5                   0
117    YES          1   625.4                   1

[118 rows x 4 columns]

### 3. Cross tabulation

In [128]:
ct = pd.crosstab(df["IS_FLOODS"], df["JUNE_MORE_THAN_500"])

print(ct)

JUNE_MORE_THAN_500   0   1
IS_FLOODS
0                   19  39
1                    6  54

### 4

In [129]:
df["JUNE_MORE_THAN_500"].mean()

np.float64(0.788135593220339)

### 5

In [131]:
df["IS_FLOODS"].mean()

np.float64(0.5084745762711864)

### 6

In [133]:
(df["IS_FLOODS"] & df["JUNE_MORE_THAN_500"]).mean()

np.float64(0.4576271186440678)

### 7

In [137]:
df[df["IS_FLOODS"] == 1]["JUNE_MORE_THAN_500"].mean()

np.float64(0.9)

### 8

In [140]:
(df["JUNE_MORE_THAN_500"] == 0).mean()

np.float64(0.211864406779661)

### 9

In [139]:
(df[df["IS_FLOODS"] == 1]["JUNE_MORE_THAN_500"] == 0).mean()

np.float64(0.1)

### 10

In [150]:
p_june_more_500 = df['JUNE_MORE_THAN_500'].mean()
p_flood = df['IS_FLOODS'].mean()
p_flood_if_june_more_500 = df[df['JUNE_MORE_THAN_500'] == 1]['IS_FLOODS'].mean()

p_june_more_500_if_flood = (p_flood_if_june_more_500 * p_june_more_500) / p_flood
print(p_june_more_500_if_flood)

0.9000000000000001

In [151]:
p_june_more_500 = df['JUNE_MORE_THAN_500'].mean()
p_june_less_500 = 1 - p_june_more_500
p_flood_june_more_500 = df[df['JUNE_MORE_THAN_500'] == 1]['IS_FLOODS'].mean() 
p_flood_june_less_500 = df[df['JUNE_MORE_THAN_500'] == 0]['IS_FLOODS'].mean()

p_june_more_500_if_flood = (p_flood_june_more_500 * p_june_more_500) / ((p_flood_june_more_500 * p_june_more_500) + (p_flood_june_less_500 * p_june_less_500))
print(p_june_more_500_if_flood)

0.8999999999999999